### ISSUE TITLE
What does this error mean exactly?

### ISSUE THREAD

**Issue by djmbritt** [brannow/sps30#2]
```
no new sensor data available (maybe bus is unstable)
```

So I'm wondering what does this mean exactly.
Sometimes it pops up, sometimes it doesn't.
When I move the GND wires around it has sometimes has en effect.
Just curious on what the specifics are.

**Comment by brannow** [comment]
it means the bus is instable (hz rate).
sadly the PI bus rate is CPU bound, any load can bring the rate out of order. 

try not to overclock the cpu, and set the
```
dtparam=i2c_arm=on
dtparam=i2c_arm_baudrate=230000
```
in the boot.txt

any other active process may cause cpu load, e.g. connect via ssh or start top.
these causes cpu spikes.

**Comment by djmbritt** [comment]
I did manage to set those parameters. 
But I was still getting that error. 

I imagine that having other sensors on the I2C bus also messes with the signal?
Or maybe I just need to do a clean install and start from scratch.

**Comment by djmbritt** [comment]
Is it normal that I keep getting the same values for pm2.5, pm4 and pm10?

**Comment by brannow** [comment]
sry for the late answer, its possible that every pm size is the same value, 
the sensor counts like: 

if 10 x pm2.5 and 5 x pm10 particle passes the sensor.
the output are
pm2.5 = 10
pm4 = 10
pm10 = 15
these are the raw sensor counting outputs.
for more information: https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/9.6_Particulate_Matter/Datasheets/Sensirion_PM_Sensors_SPS30_Datasheet.pdf

so is everything smaller or equal pm2.5, it is possible.

here is another project with the same question: https://github.com/paulvha/sps30/issues/3#issuecomment-618438716
/closed

**Comment by djmbritt** [comment]
Hi brannow,
Thanks for the time and the insight 🙏🏽

**Comment by brannow** [comment]
I reopen this ticket, cuz there is a problem in the reading 2.5, 4 and 10.

it seems more like a firmware bug in sps30 to me other reading projects shown the same problems.
